package com.DMDA.Lab09_10;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class Lab0910Application {

	public static void main(String[] args) {
		SpringApplication.run(Lab0910Application.class, args);
	}

}
